In [11]:
import numpy as np
from sklearn.preprocessing import StandardScaler


In [2]:
data = np.array([[50,30],[20,90],[30,50]])

In [7]:
ss=StandardScaler()

In [8]:
ss.fit(data)

/Users/sushanta/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [14]:
ss.transform(data)

/Users/sushanta/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 1.33630621, -1.06904497],
       [-1.06904497,  1.33630621],
       [-0.26726124, -0.26726124]])

In [18]:
np.std(data,axis=0)

array([12.47219129, 24.94438258])

In [20]:
(data-np.std(data,axis=0))/np.std(data,axis=0)

array([[3.00891863, 0.20267559],
       [0.60356745, 2.60802677],
       [1.40535118, 1.00445931]])